### ISSUE TITLE
Regarding general direction of use

### ISSUE THREAD

**Issue by TwistingTwists** [am-kantox/estructura#9]
Hello,

I read the documentation. I am planning to use this package into my existing project to reduce a lot of boilerplate - mainly around validation. 

1. Are there some obvious limitations I should be aware of ? (Which are not in documentation)
2. What is the future direction of the project?

**Comment by am-kantox** [comment]
Hello @TwistingTwist, sorry for the late response.

There are no limitations I am currently aware of. I am not sure about the future direction of the project because now it seems to be complete. After some time and possible bugs found, I’ll make it `v1.0`. If something new will come into my mind, it would probably leak into the project, but for now I think it does not require any further features.

**Comment by TwistingTwists** [comment]
That gives me a lot of confidence to start using it. 

Thank you so much for reply!
